//! Orchestration for verified MIR-to-C11 lowering.
//!
//! This module owns phase order only: verify, validate the deliberately narrow
//! experimental subset, collect helpers, and emit deterministic C. Semantic
//! decisions stay in canonical MIR rather than being reconstructed here.
use crate::api::{CBackendError, CLoweringOptions, CTranslationUnit};
use crate::emission::*;
use crate::validation::validate_bubble;
use pop_mir::{MirBubble, verify_mir_bubble};
use pop_types::{FloatKind, TypeArena};
/// Lowers one verified runtime-free MIR Bubble to deterministic ISO C11.
///
/// # Errors
///
/// Rejects invalid MIR, unsupported runtime/type operations, and an invalid
/// requested entry point before returning any translation unit.
pub fn lower_mir_to_c(
    bubble: &MirBubble,
    types: &TypeArena,
    options: CLoweringOptions,
) -> Result<CTranslationUnit, CBackendError> {
    verify_mir_bubble(bubble, types).map_err(CBackendError::MirVerification)?;
    validate_bubble(bubble, types, options)?;

    let helpers = collect_checked_helpers(bubble);
    let float_helpers = collect_float_helpers(bubble);
    let standard_calls = collect_standard_calls(bubble);
    let needs_trap = !helpers.is_empty() || contains_explicit_trap(bubble);
    let mut output = String::from(
        "/* Generated by Pop Lang's experimental C backend. */\n\
         #include <stdbool.h>\n\
         #include <stddef.h>\n\
         #include <stdint.h>\n\
         #include <inttypes.h>\n\
         #include <stdio.h>\n\
         #include <stdlib.h>\n\
         #include <string.h>\n\
         #include <limits.h>\n\n\
         #include <float.h>\n\n\
         #if !defined(__STDC_IEC_559__)\n\
         #error \"Pop Lang C output requires IEC 60559 floating-point semantics\"\n\
         #endif\n\n\
         _Static_assert(CHAR_BIT == 8, \"Pop Lang requires 8-bit bytes\");\n\
         _Static_assert(FLT_RADIX == 2, \"Pop Lang requires binary floating point\");\n\
         _Static_assert(sizeof(float) == 4, \"Pop Float32 requires 32-bit float\");\n\
         _Static_assert(sizeof(double) == 8, \"Pop Float64 requires 64-bit double\");\n\n",
    );
    if needs_trap {
        output.push_str("static _Noreturn void pop_trap(void) { abort(); }\n\n");
    }
    if float_helpers.contains(&FloatKind::Float32) {
        output.push_str(
            "static float pop_float32_from_bits(uint32_t bits)\n\
             {\n\
                 float value;\n\
                 memcpy(&value, &bits, sizeof(value));\n\
                 return value;\n\
             }\n\n",
        );
    }
    if float_helpers.contains(&FloatKind::Float64) {
        output.push_str(
            "static double pop_float64_from_bits(uint64_t bits)\n\
             {\n\
                 double value;\n\
                 memcpy(&value, &bits, sizeof(value));\n\
                 return value;\n\
             }\n\n",
        );
    }
    if standard_calls.contains(&1) {
        output.push_str(
            "typedef struct\n\
             {\n\
                 const unsigned char *data;\n\
                 size_t length;\n\
             } pop_string;\n\n",
        );
    }
    if standard_calls.contains(&0) {
        output.push_str(
            "static void pop_print_int(int64_t value)\n\
             {\n\
                 (void)printf(\"%\" PRId64 \"\\n\", value);\n\
             }\n\n",
        );
    }
    if standard_calls.contains(&1) {
        output.push_str(
            "static void pop_print_string(pop_string value)\n\
             {\n\
                 (void)fwrite(value.data, 1, value.length, stdout);\n\
                 (void)fputc('\\n', stdout);\n\
             }\n\n",
        );
    }
    for helper in helpers {
        emit_checked_helper(&mut output, helper);
    }
    emit_string_literals(&mut output, bubble);
    for function in bubble.functions() {
        emit_function_declaration(&mut output, bubble, function, types)?;
    }
    output.push('\n');
    for function in bubble.functions() {
        emit_function(&mut output, bubble, function, types)?;
    }
    if let Some(entry) = options.entry_point {
        emit_entry(&mut output, bubble, types, entry)?;
    }
    Ok(CTranslationUnit(output))
}
