//! Deterministic ADR 0093 `.popc` binding generation.

use std::error::Error;
use std::fmt;
use std::fmt::Write as _;
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Component, Path, PathBuf};

use pop_projects::{ManifestError, PackageManifest, parse_package_manifest};
use pop_target::TargetSpec;
use sha2::{Digest, Sha256};

mod descriptor;

use descriptor::{Descriptor, parse_descriptor, parse_generated_metadata, render_declarations};

const MAX_MANIFEST_BYTES: usize = 1024 * 1024;
const GENERATED_SOURCE: &str = "bindings.pop";
const GENERATED_SHIM: &str = "bindings.c";
const GENERATED_METADATA: &str = "native-bindings.popc";
const NO_SHIM_SOURCE: &str = "/* Generated by pop ffi generate; schema 1 has no C shims. */\n";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FfiGenerationErrorKind {
    InvalidManifest,
    InvalidInput,
    InvalidDescriptor,
    ResourceLimit,
    PolicyMismatch,
    UnsupportedAbi,
    OutputConflict,
    PublicationIo,
}

impl FfiGenerationErrorKind {
    #[must_use]
    pub const fn diagnostic_code(self) -> &'static str {
        match self {
            Self::InvalidManifest => "POP5080",
            Self::InvalidInput => "POP5081",
            Self::InvalidDescriptor => "POP5082",
            Self::ResourceLimit => "POP5083",
            Self::PolicyMismatch => "POP5084",
            Self::UnsupportedAbi => "POP5085",
            Self::OutputConflict => "POP5086",
            Self::PublicationIo => "POP5087",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FfiGenerationError {
    kind: FfiGenerationErrorKind,
    reason: String,
}

impl FfiGenerationError {
    pub(crate) fn new(kind: FfiGenerationErrorKind, reason: impl Into<String>) -> Self {
        Self {
            kind,
            reason: reason.into(),
        }
    }

    #[must_use]
    pub const fn kind(&self) -> FfiGenerationErrorKind {
        self.kind
    }

    #[must_use]
    pub const fn diagnostic_code(&self) -> &'static str {
        self.kind.diagnostic_code()
    }

    #[must_use]
    pub fn reason(&self) -> &str {
        &self.reason
    }
}

impl fmt::Display for FfiGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "{}: {}",
            self.kind.diagnostic_code(),
            self.reason
        )
    }
}

impl Error for FfiGenerationError {}

/// Generates one exact target-selected ADR 0093 binding directory.
///
/// # Errors
///
/// Returns one typed stable-code error before publishing any partial output.
pub fn generate_ffi_bindings(
    manifest_path: &Path,
    platform_target: &str,
    alias: &str,
) -> Result<(), FfiGenerationError> {
    if manifest_path.file_name().and_then(|name| name.to_str()) != Some("bubble.toml") {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidManifest,
            "manifest path must name bubble.toml",
        ));
    }
    let package_root = manifest_path.parent().ok_or_else(|| {
        FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidManifest,
            "manifest has no package root",
        )
    })?;
    verify_directory(package_root, FfiGenerationErrorKind::InvalidInput)?;
    let manifest_bytes = read_regular_file(manifest_path, MAX_MANIFEST_BYTES, false)?;
    let manifest_text = std::str::from_utf8(&manifest_bytes).map_err(|_| {
        FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidManifest,
            "manifest is not UTF-8",
        )
    })?;
    let manifest = parse_package_manifest(manifest_text).map_err(manifest_error)?;
    let generation = load_expected_generation(package_root, &manifest, platform_target, alias)?;
    let outputs = generation.outputs();
    if generation.output_path.exists() {
        return verify_existing_generation(
            &generation.output_path,
            &outputs,
            &generation.descriptor,
            &generation.target,
        );
    }
    publish_generation(
        &generation.output_path,
        &outputs,
        &generation.descriptor,
        &generation.target,
    )
}

/// Verifies every selected ADR 0093 generated directory before Package source
/// discovery or compilation.
///
/// # Errors
///
/// Rejects missing, extra, symlinked, malformed, noncanonical, target-mismatched,
/// or hash-mismatched generated output without modifying the Package.
pub fn verify_ffi_generated_bindings(
    package_root: &Path,
    manifest: &PackageManifest,
    platform_target: &str,
) -> Result<(), FfiGenerationError> {
    verify_directory(package_root, FfiGenerationErrorKind::InvalidInput)?;
    let Some(platform) = manifest
        .platform_ffi_generators()
        .iter()
        .find(|platform| platform.platform_target() == platform_target)
    else {
        return Ok(());
    };
    for generator in platform.generators() {
        let generation =
            load_expected_generation(package_root, manifest, platform_target, generator.alias())?;
        if !generation.output_path.exists() {
            return Err(FfiGenerationError::new(
                FfiGenerationErrorKind::OutputConflict,
                format!(
                    "generated output for alias `{}` and target `{platform_target}` is missing",
                    generator.alias(),
                ),
            ));
        }
        verify_existing_generation(
            &generation.output_path,
            &generation.outputs(),
            &generation.descriptor,
            &generation.target,
        )?;
    }
    Ok(())
}

struct ExpectedGeneration {
    output_path: PathBuf,
    descriptor: Descriptor,
    target: TargetSpec,
    source: String,
    shim: String,
    metadata: String,
}

impl ExpectedGeneration {
    fn outputs(&self) -> [(&'static str, &[u8]); 3] {
        [
            (GENERATED_SOURCE, self.source.as_bytes()),
            (GENERATED_SHIM, self.shim.as_bytes()),
            (GENERATED_METADATA, self.metadata.as_bytes()),
        ]
    }
}

fn load_expected_generation(
    package_root: &Path,
    manifest: &PackageManifest,
    platform_target: &str,
    alias: &str,
) -> Result<ExpectedGeneration, FfiGenerationError> {
    let generator = manifest
        .ffi_generator(platform_target, alias)
        .map_err(manifest_error)?;
    let target = TargetSpec::for_triple(platform_target).map_err(|error| {
        FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidManifest,
            format!("unsupported platform target: {error}"),
        )
    })?;
    let descriptor_path = verified_relative_file(package_root, generator.descriptor())?;
    let descriptor_bytes = read_regular_file(&descriptor_path, 4 * 1024 * 1024, true)?;
    let descriptor_hash = sha256_hex(&descriptor_bytes);
    if descriptor_hash != generator.descriptor_sha256() {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidInput,
            "descriptor SHA-256 does not match the manifest",
        ));
    }
    let descriptor = parse_descriptor(&descriptor_bytes, &target)?;
    let source = render_source(&descriptor, generator.native_library());
    let shim = NO_SHIM_SOURCE.to_owned();
    let metadata = render_metadata(
        &descriptor,
        GenerationIdentity {
            alias,
            native_library: generator.native_library(),
            descriptor_path: generator.descriptor(),
            descriptor_sha256: &descriptor_hash,
        },
        &source,
        &shim,
    );
    verify_metadata(&metadata, &descriptor, &source, &shim, &target)?;
    let output_path = verified_relative_output(package_root, generator.output_directory())?;
    Ok(ExpectedGeneration {
        output_path,
        descriptor,
        target,
        source,
        shim,
        metadata,
    })
}

fn manifest_error(error: ManifestError) -> FfiGenerationError {
    FfiGenerationError::new(FfiGenerationErrorKind::InvalidManifest, error.to_string())
}

fn render_source(descriptor: &Descriptor, native_library: Option<&str>) -> String {
    let mut output = String::new();
    if let Some(native_library) = native_library {
        writeln!(output, "@Ffi.Link(\"{native_library}\")").expect("String write");
    }
    writeln!(output, "namespace {}", descriptor.output_namespace).expect("String write");
    render_declarations(descriptor, &mut output, false);
    output
}

#[derive(Clone, Copy)]
struct GenerationIdentity<'a> {
    alias: &'a str,
    native_library: Option<&'a str>,
    descriptor_path: &'a str,
    descriptor_sha256: &'a str,
}

fn render_metadata(
    descriptor: &Descriptor,
    identity: GenerationIdentity<'_>,
    source: &str,
    shim: &str,
) -> String {
    let native_library = identity.native_library.unwrap_or("");
    let mut output = String::new();
    output.push_str("@Ffi.GeneratedBindings(\n");
    output.push_str("    schemaVersion = 1,\n");
    writeln!(
        output,
        "    generatorVersion = \"{}\",",
        env!("CARGO_PKG_VERSION")
    )
    .expect("String write");
    output.push_str("    parserVersion = 1,\n");
    writeln!(output, "    alias = \"{}\",", identity.alias).expect("String write");
    writeln!(
        output,
        "    platformTarget = \"{}\",",
        descriptor.platform_target
    )
    .expect("String write");
    writeln!(output, "    nativeLibrary = \"{native_library}\",").expect("String write");
    writeln!(
        output,
        "    producerName = \"{}\",",
        descriptor.producer_name
    )
    .expect("String write");
    writeln!(
        output,
        "    producerVersion = \"{}\",",
        descriptor.producer_version
    )
    .expect("String write");
    writeln!(
        output,
        "    descriptorPath = \"{}\",",
        identity.descriptor_path
    )
    .expect("String write");
    writeln!(
        output,
        "    descriptorSha256 = \"{}\",",
        identity.descriptor_sha256
    )
    .expect("String write");
    writeln!(
        output,
        "    abiFingerprint = \"{}\",",
        identity.descriptor_sha256
    )
    .expect("String write");
    writeln!(output, "    sourcePath = \"{GENERATED_SOURCE}\",").expect("String write");
    writeln!(output, "    sourceSize = {},", source.len()).expect("String write");
    writeln!(
        output,
        "    sourceSha256 = \"{}\",",
        sha256_hex(source.as_bytes())
    )
    .expect("String write");
    writeln!(output, "    shimPath = \"{GENERATED_SHIM}\",").expect("String write");
    writeln!(output, "    shimSize = {},", shim.len()).expect("String write");
    writeln!(
        output,
        "    shimSha256 = \"{}\",",
        sha256_hex(shim.as_bytes())
    )
    .expect("String write");
    writeln!(
        output,
        "    outputNamespace = {},",
        descriptor.output_namespace
    )
    .expect("String write");
    writeln!(output, ")\nnamespace {}", descriptor.binding_namespace).expect("String write");
    render_declarations(descriptor, &mut output, true);
    output
}

fn verify_metadata(
    metadata: &str,
    descriptor: &Descriptor,
    source: &str,
    shim: &str,
    target: &TargetSpec,
) -> Result<(), FfiGenerationError> {
    let parsed = parse_generated_metadata(metadata.as_bytes(), target)?;
    if parsed.descriptor != *descriptor
        || parsed.generator_version != env!("CARGO_PKG_VERSION")
        || parsed.parser_version != 1
        || parsed.source_path != GENERATED_SOURCE
        || parsed.source_size != u64::try_from(source.len()).expect("output size fits u64")
        || parsed.source_sha256 != sha256_hex(source.as_bytes())
        || parsed.shim_path != GENERATED_SHIM
        || parsed.shim_size != u64::try_from(shim.len()).expect("output size fits u64")
        || parsed.shim_sha256 != sha256_hex(shim.as_bytes())
        || parsed.descriptor_sha256 != parsed.abi_fingerprint
    {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::PublicationIo,
            "generated metadata failed its typed inventory postcondition",
        ));
    }
    Ok(())
}

fn verify_directory(path: &Path, kind: FfiGenerationErrorKind) -> Result<(), FfiGenerationError> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| io_error(kind, "could not inspect directory", error))?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(FfiGenerationError::new(
            kind,
            "path is not a regular non-symlinked directory",
        ));
    }
    Ok(())
}

fn verified_relative_file(root: &Path, relative: &str) -> Result<PathBuf, FfiGenerationError> {
    let mut path = root.to_path_buf();
    let mut components = Path::new(relative).components().peekable();
    while let Some(component) = components.next() {
        let Component::Normal(component) = component else {
            return Err(FfiGenerationError::new(
                FfiGenerationErrorKind::InvalidInput,
                "descriptor path escapes the Package",
            ));
        };
        path.push(component);
        let metadata = fs::symlink_metadata(&path).map_err(|error| {
            io_error(
                FfiGenerationErrorKind::InvalidInput,
                "could not inspect descriptor path",
                error,
            )
        })?;
        if metadata.file_type().is_symlink()
            || (components.peek().is_some() && !metadata.is_dir())
            || (components.peek().is_none() && !metadata.is_file())
        {
            return Err(FfiGenerationError::new(
                FfiGenerationErrorKind::InvalidInput,
                "descriptor path must contain only regular non-symlinked components",
            ));
        }
    }
    Ok(path)
}

fn verified_relative_output(root: &Path, relative: &str) -> Result<PathBuf, FfiGenerationError> {
    let mut path = root.to_path_buf();
    let mut components = Path::new(relative).components().peekable();
    if components.peek().is_none() {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidInput,
            "output directory must be Package-relative",
        ));
    }
    let mut prefix_exists = true;
    while let Some(component) = components.next() {
        let Component::Normal(component) = component else {
            return Err(FfiGenerationError::new(
                FfiGenerationErrorKind::InvalidInput,
                "output directory must be a normalized Package-relative path",
            ));
        };
        path.push(component);
        if !prefix_exists {
            continue;
        }
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(FfiGenerationError::new(
                    FfiGenerationErrorKind::InvalidInput,
                    "output path cannot contain a symlink",
                ));
            }
            Ok(metadata) if components.peek().is_some() && !metadata.is_dir() => {
                return Err(FfiGenerationError::new(
                    FfiGenerationErrorKind::InvalidInput,
                    "output parent must contain only directories",
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                prefix_exists = false;
            }
            Err(error) => {
                return Err(io_error(
                    FfiGenerationErrorKind::InvalidInput,
                    "could not inspect output path",
                    error,
                ));
            }
        }
    }
    Ok(path)
}

fn read_regular_file(
    path: &Path,
    maximum_bytes: usize,
    descriptor_input: bool,
) -> Result<Vec<u8>, FfiGenerationError> {
    let kind = if descriptor_input {
        FfiGenerationErrorKind::InvalidInput
    } else {
        FfiGenerationErrorKind::InvalidManifest
    };
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| io_error(kind, "could not inspect input file", error))?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(FfiGenerationError::new(
            kind,
            "input must be a regular non-symlinked file",
        ));
    }
    if metadata.len() > u64::try_from(maximum_bytes).expect("schema limit fits u64") {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::ResourceLimit,
            "input exceeds its deterministic size budget",
        ));
    }
    let file =
        File::open(path).map_err(|error| io_error(kind, "could not open input file", error))?;
    let mut bytes = Vec::with_capacity(usize::try_from(metadata.len()).unwrap_or(maximum_bytes));
    file.take(u64::try_from(maximum_bytes + 1).expect("schema limit fits u64"))
        .read_to_end(&mut bytes)
        .map_err(|error| io_error(kind, "could not read input file", error))?;
    if bytes.len() > maximum_bytes {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::ResourceLimit,
            "input changed beyond its deterministic size budget",
        ));
    }
    Ok(bytes)
}

fn ensure_parent_directories(root: &Path, output: &Path) -> Result<(), FfiGenerationError> {
    let parent = output.parent().ok_or_else(|| {
        FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidInput,
            "output has no parent directory",
        )
    })?;
    let relative = parent.strip_prefix(root).map_err(|_| {
        FfiGenerationError::new(
            FfiGenerationErrorKind::InvalidInput,
            "output escapes the Package root",
        )
    })?;
    let mut current = root.to_path_buf();
    for component in relative.components() {
        let Component::Normal(component) = component else {
            return Err(FfiGenerationError::new(
                FfiGenerationErrorKind::InvalidInput,
                "output path is not normalized",
            ));
        };
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_dir() => {
                return Err(FfiGenerationError::new(
                    FfiGenerationErrorKind::InvalidInput,
                    "output parent contains a non-directory or symlink",
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                fs::create_dir(&current).map_err(|error| {
                    io_error(
                        FfiGenerationErrorKind::PublicationIo,
                        "could not create output parent",
                        error,
                    )
                })?;
            }
            Err(error) => {
                return Err(io_error(
                    FfiGenerationErrorKind::PublicationIo,
                    "could not inspect output parent",
                    error,
                ));
            }
        }
    }
    Ok(())
}

fn publish_generation(
    output: &Path,
    files: &[(&str, &[u8])],
    descriptor: &Descriptor,
    target: &TargetSpec,
) -> Result<(), FfiGenerationError> {
    let package_root = output
        .ancestors()
        .find(|path| path.join("bubble.toml").is_file())
        .ok_or_else(|| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::InvalidInput,
                "output is not inside a Package root",
            )
        })?;
    ensure_parent_directories(package_root, output)?;
    let parent = output.parent().expect("verified output parent");
    let leaf = output
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::InvalidInput,
                "output directory name is not UTF-8",
            )
        })?;
    let staging = parent.join(format!(".{leaf}.{}.tmp", std::process::id()));
    if staging.exists() {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::OutputConflict,
            "private generation staging directory already exists",
        ));
    }
    fs::create_dir(&staging).map_err(|error| {
        io_error(
            FfiGenerationErrorKind::PublicationIo,
            "could not create private generation staging directory",
            error,
        )
    })?;
    let write_result = (|| {
        for (name, bytes) in files {
            let path = staging.join(name);
            let mut file = OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&path)
                .map_err(|error| {
                    io_error(
                        FfiGenerationErrorKind::PublicationIo,
                        "could not create staged output",
                        error,
                    )
                })?;
            file.write_all(bytes).map_err(|error| {
                io_error(
                    FfiGenerationErrorKind::PublicationIo,
                    "could not write staged output",
                    error,
                )
            })?;
            file.sync_all().map_err(|error| {
                io_error(
                    FfiGenerationErrorKind::PublicationIo,
                    "could not synchronize staged output",
                    error,
                )
            })?;
        }
        let mut reloaded = Vec::with_capacity(files.len());
        for (name, expected) in files {
            let actual =
                read_regular_file(&staging.join(name), expected.len(), true).map_err(|_| {
                    FfiGenerationError::new(
                        FfiGenerationErrorKind::PublicationIo,
                        "staged output is not a regular complete file",
                    )
                })?;
            if actual != *expected || sha256_hex(&actual) != sha256_hex(expected) {
                return Err(FfiGenerationError::new(
                    FfiGenerationErrorKind::PublicationIo,
                    "staged output changed before publication",
                ));
            }
            reloaded.push(actual);
        }
        let source = std::str::from_utf8(&reloaded[0]).map_err(|_| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::PublicationIo,
                "staged source is not UTF-8",
            )
        })?;
        let shim = std::str::from_utf8(&reloaded[1]).map_err(|_| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::PublicationIo,
                "staged shim is not UTF-8",
            )
        })?;
        let metadata = std::str::from_utf8(&reloaded[2]).map_err(|_| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::PublicationIo,
                "staged metadata is not UTF-8",
            )
        })?;
        verify_metadata(metadata, descriptor, source, shim, target)?;
        // `std` has no portable rename-with-no-replace for directories. Check
        // immediately before the atomic rename and fail closed on any visible
        // destination; the rename itself remains the publication boundary.
        match fs::symlink_metadata(output) {
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Ok(_) => {
                return Err(FfiGenerationError::new(
                    FfiGenerationErrorKind::OutputConflict,
                    "generated output appeared during publication",
                ));
            }
            Err(error) => {
                return Err(io_error(
                    FfiGenerationErrorKind::PublicationIo,
                    "could not recheck generated output",
                    error,
                ));
            }
        }
        fs::rename(&staging, output).map_err(|error| {
            io_error(
                FfiGenerationErrorKind::PublicationIo,
                "could not atomically publish generated bindings",
                error,
            )
        })?;
        Ok(())
    })();
    if write_result.is_err() && staging.exists() {
        let _ = fs::remove_dir_all(&staging);
    }
    write_result
}

fn verify_existing_generation(
    output: &Path,
    files: &[(&str, &[u8])],
    descriptor: &Descriptor,
    target: &TargetSpec,
) -> Result<(), FfiGenerationError> {
    let metadata = fs::symlink_metadata(output).map_err(|error| {
        io_error(
            FfiGenerationErrorKind::OutputConflict,
            "could not inspect existing generated output",
            error,
        )
    })?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::OutputConflict,
            "generated output conflicts with a non-directory or symlink",
        ));
    }
    let mut names = fs::read_dir(output)
        .map_err(|error| {
            io_error(
                FfiGenerationErrorKind::OutputConflict,
                "could not inspect existing generated output",
                error,
            )
        })?
        .map(|entry| entry.map(|entry| entry.file_name()))
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| {
            io_error(
                FfiGenerationErrorKind::OutputConflict,
                "could not inspect existing generated output",
                error,
            )
        })?;
    names.sort();
    let mut expected_names = files
        .iter()
        .map(|(name, _)| std::ffi::OsString::from(name))
        .collect::<Vec<_>>();
    expected_names.sort();
    if names != expected_names {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::OutputConflict,
            "existing output is not the same complete generated file set",
        ));
    }
    let metadata_path = output.join(GENERATED_METADATA);
    let metadata_bytes =
        read_regular_file(&metadata_path, 4 * 1024 * 1024, true).map_err(|_| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::OutputConflict,
                "generated metadata is missing, symlinked, or unreadable",
            )
        })?;
    let parsed = parse_generated_metadata(&metadata_bytes, target)?;
    if parsed.descriptor != *descriptor {
        return Err(FfiGenerationError::new(
            FfiGenerationErrorKind::PolicyMismatch,
            "generated metadata descriptor does not match the selected manifest input",
        ));
    }
    for (name, expected) in files {
        let path = output.join(name);
        let actual = read_regular_file(&path, expected.len(), true).map_err(|_| {
            FfiGenerationError::new(
                FfiGenerationErrorKind::OutputConflict,
                "existing generated file is unreadable or unsafe",
            )
        })?;
        if actual != *expected {
            return Err(FfiGenerationError::new(
                FfiGenerationErrorKind::OutputConflict,
                "existing generated output differs from the requested generation",
            ));
        }
    }
    let source = std::str::from_utf8(files[0].1).expect("generated source is canonical UTF-8");
    let shim = std::str::from_utf8(files[1].1).expect("generated shim is canonical UTF-8");
    let metadata = std::str::from_utf8(files[2].1).expect("generated metadata is canonical UTF-8");
    verify_metadata(metadata, descriptor, source, shim, target)?;
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .fold(String::with_capacity(64), |mut output, byte| {
            write!(output, "{byte:02x}").expect("String write");
            output
        })
}

#[allow(clippy::needless_pass_by_value)] // Own the source error at the typed diagnostic boundary.
fn io_error(
    kind: FfiGenerationErrorKind,
    context: &str,
    error: std::io::Error,
) -> FfiGenerationError {
    FfiGenerationError::new(kind, format!("{context}: {error}"))
}
